### ISSUE TITLE
Do not add type prop when component is not button or input

### ISSUE THREAD

**Issue by nene** [nihey/react-clipboard.js#28]
I'd like to render the ClipboardButton as simple div, so I write:

    <CliboardButton component="div"/>

which will result in:

    <div type="button"/>

In my case this conflicts with [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) which has rules like:

```css
button,
html [type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}
```

resulting in div rendered with a look of a button. My current workaround is to use some silly value for the `type` prop:

    <CliboardButton component="div" type="blah"/>
